### ISSUE TITLE
[Bug] Player walk animation stuck as baby when removing addon

### ISSUE THREAD

**Issue by Skyesinic** [YutaYamamoto212/BabyMobsAddon#1]
### Description of the Bug

Player walk animation stuck as baby when removing addon. 

### Steps to Reproduce

```bash
1. Add baby mobs addon with player setting
2. Remove addon from world
3. Player still stuck with baby leg animation when walking
```

### Expected Behavior

Player walk animation returns to normal

### Actual Behavior

Player animation stays the same even after addon is removed

### Baby Mobs Addon Version

1.0.1

### What is the game version you are playing?

1.19.20

### What is the system of the device you are using?

Windows

**Comment by YutaYamamoto212** [comment]
Confirmed to be affected in game versions 1.19.20, 1.19.30, 1.19.40 and 1.19.50.

**Comment by YutaYamamoto212** [comment]
I tried to overwrite the player's attributes back with the vanilla data, but the bug continued.
Also, removing behavior packs is not officially recommended by Minecraft.
Therefore, this bug cannot be fixed and is closed as **Won't Fix**.
